FROM node:20-alpine
LABEL authors="Sysoienko"

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы
COPY . .

# Собираем приложение
RUN npm run build

# Запускаем сервер
CMD ["npm", "run", "start"]