services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '3001:3000' # Зовні буде доступний на http://localhost:3001
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - app-network

#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend
#    ports:
#      - '3000:3000' # Next.js працює на 3000
#    env_file:
#      - ./frontend/.env
#    depends_on:
#      - backend
#    networks:
#      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge